config/routes.rb
Rails.application.routes.draw do
  root "translations#new"
  resources :translations
  get 'test', to: "translations#show", as: "show_translation"

  
  get "/admin" => "admin/languages#index"
  namespace :admin do
    resources :languages
  end  

end

app/models/admin/language.rb
class Language < ActiveRecord::Base
  has_many :words, class_name: "Translation", foreign_key: "word_language_id"
  has_many :translations, class_name: "Translation", foreign_key: "translation_language_id"
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :words, class_name: "Translation", foreign_key: "word_language_id"
  has_many :translations, class_name: "Translation", foreign_key: "translation_language_id"
end

app/models/translation.rb
class Translation < ActiveRecord::Base
  belongs_to :word_language, class_name: "Language", inverse_of: :words, foreign_key: "word_language_id"
  belongs_to :translation_language, class_name: "Language", inverse_of: :translations, foreign_key: "translation_language_id"

  
  def self.create_from_file(path)
    extension = path.scan(/([^\.]+)$/)[0][0]
    case extension 
    when "xlsx"
      s = Roo::Excelx.new(path)
      s.default_sheet = s.sheets.first
      (1..s.last_row).each do |row|
        Translation.create(word: s.cell(row,1), translation: s.cell(row,2), word_language_id: 1, translation_language_id: 2)
      end
    when "csv"
      s = Roo::CSV.new(path)
      s.default_sheet = s.sheets.first
      (1..s.last_row).each do |row|
        Translation.create(word: s.cell(row,1), translation: s.cell(row,2), word_language_id: 1, translation_language_id: 2)
      end
    when "xls"
      s = Roo::Spreadsheet.open(path)
      s.each do |row|
        Translation.create(word: row[0], translation: row[1], word_language_id: 1, translation_language_id: 2)
      end
    else
    end
  end

  def percent
    if translation_count == 0
      return 0
    else
      (success_translation_count.to_f / translation_count * 100).round(2)
    end
  end

end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  
  http_basic_authenticate_with name: "admin", password: "admin"
  protect_from_forgery with: :exception

  layout "application"
end

app/controllers/admin/languages_controller.rb
class Admin::LanguagesController < Admin::ApplicationController

  def index
    @languages = Language.all
  end

  def show
    unless @language = Language.where(id: params[:id]).first
      render text: "Page not found", status: 404
    end
  end

  def new
    @language = Language.new
  end

  def create
    @language = Language.create(languages_params)
    if @language.errors.empty?
      redirect_to language_path(@language)
    else 
      render "new"
    end
  end

  def edit
    @language = Language.where(id: params[:id]).first
  end

  def update
    if @language.update(languages_params)
      redirect_to @percent, notice: 'Percent was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @language = Language.where(id: params[:id]).first
    @language.destroy
  end

  private

    def languages_params
      params.require(:language).permit(:name, :key)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController

  def index
    @translations = Translation.all
  end

  def show
    if params[:id].nil?
      @translation = Translation.order("RANDOM()").first
    else
      redirect_to show_translation_path
    end
  end

  def new
  end
  
  def create
    return render action: "new" if params[:file].nil?
    uploaded_io = params[:file]
    path = "public/uploads/#{uploaded_io.original_filename}"
    File.open(Rails.root.join('public', 'uploads',uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
    end
    return render :text => "File have other path" if Translation.create_from_file(path).nil?
    redirect_to translations_path
  end

  def update
    @translation = Translation.where(id: params[:id]).first
    @translation.update(translation_count: (@translation.translation_count + 1))
    if params[:success] == true 
      @translation.update(success_translation_count: @translation.success_translation_count + 1)
    end
    #render json: { success: true }
    redirect_to show_translation_path
  end

  def destroy 
    @translation = Translation.find(params[:id])
    @translation.destroy
    render json: { success: true }
  end

end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/languages_helper.rb
module Admin::LanguagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/admin/languages/_form.html.haml
= form_for [:admin, @language] do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :key, class: 'control-label'
    .controls
      = f.text_field :key, class: 'form-control'
  = f.submit nil, class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_languages_path, :class => 'btn btn-default'

app/views/admin/languages/edit.html.haml
%h3 Edit
= render partial: 'form'

app/views/admin/languages/index.html.haml
%h1 Languages
%table.table
  %tr
    %th Name
    %th Key
  - @languages.each do |l|
    %tr
      %td= l.name
      %td= l.key

app/views/admin/languages/new.html.haml
%h3 New
= render partial: 'form'

app/views/admin/languages/show.html.haml
%h1 Languages#show
%p Find me in app/views/languages/show.html.haml

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dictionary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Dictionary"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href=translations_path) Dictionary
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Load new words", new_translation_path
            %li= link_to "Test of knowledge", show_translation_path, class: "test-knowledge"
            %li= link_to "Languages", admin_languages_path

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "#"
              %li= link_to "Link 2", "#"
              %li= link_to "Link 3", "#"
      %footer
        %p &copy; davinci 2.0

app/views/translations/index.html.haml
%h1 #{Language.first.key}-#{Language.last.key}
%table.table
  %tr
    %th Word
    %th Translation
    %th Count
    %th Success count
    %th Success percent
    %th
  - @translations.each do |t|
    %tr{data: {:translation_id => "#{t.id}"}}
      %td= t.word
      %td= t.translation
      %td= t.translation_count
      %td= t.success_translation_count
      %td #{t.percent} %
      %td
        %span.deleteAction.btn.btn-link delete
      

app/views/translations/new.html.haml
= form_tag translations_path, :method => :post, :multipart => true do
  = file_field_tag 'file', :calss => ''
  = submit_tag "Load", :class => 'btn btn-success load-btn btn-sm'

app/views/translations/show.html.haml
%p= @translation.translation
%div  
  %div.btn.btn-success.btn-show-word
    %div.text-show-word Show Word
    %div.show-word= @translation.word
  %br
  %br
  %div{data: {translation_id: "#{@translation.id}"}}
    %button{type: "button", class: "btn btn-success btn-translate"} Перевел
    %button{type: "button", class: "btn btn-danger btn-not-translate"} Не перевел